export let keywords = [
  "GeniusXP",
  "Genius",
  "eventos",
  "experiência",
  "engajamento",
  "participantes",
  "inteligência artificial",
  "gestão de eventos",
  "evento 360",
  "plataforma de eventos",
  "organização de eventos",
  "análise de dados",
  "AI para eventos",
  "eventos corporativos",
  "tecnologia em eventos",
  "análise de sentimento",
  "otimização de eventos",
  "personalização de eventos",
  "insights de eventos",
  "pós-evento",
  "pré-evento",
  "gestão de participantes",
  "eventos digitais",
  "eventos híbridos",
  "experiência do participante",
  "gestão de leads",
  "ferramenta para eventos",
  "automatização de eventos",
  "interação em eventos",
  "análise de emoções",
  "marketing de eventos",
  "vendas de ingressos",
  "melhor plataforma de eventos",
  "inteligência em eventos",
  "AI em eventos",
  "futuro dos eventos",
  "eventos com AI",
  "gestão inteligente de eventos",
  "solução para eventos",
];