export let keywords = [
  "GeniusXP",
  "Genius",
  "Genius XP",
  "Genius Experience",
  "Genius Experience Platform",
  "plataforma GeniusXP",
  "eventos",
  "experiência",
  "engajamento",
  "participantes",
  "inteligência artificial",
  "gestão de eventos",
  "evento 360",
  "plataforma de eventos",
  "organização de eventos",
  "análise de dados",
  "IA para eventos",
  "eventos corporativos",
  "tecnologia em eventos",
  "análise de sentimento",
  "otimização de eventos",
  "personalização de eventos",
  "insights de eventos",
  "pós-evento",
  "pré-evento",
  "gestão de participantes",
  "eventos digitais",
  "eventos híbridos",
  "experiência do participante",
  "gestão de leads",
  "ferramenta para eventos",
  "automatização de eventos",
  "interação em eventos",
  "análise de emoções",
  "marketing de eventos",
  "vendas de ingressos",
  "melhor plataforma de eventos",
  "inteligência em eventos",
  "AI em eventos",
  "futuro dos eventos",
  "eventos com AI",
  "gestão inteligente de eventos",
  "solução para eventos",
  "FIAP",
  "FIAP NEXT",
  "FIAP NEXT 2024",
  "Plusoft",
  "IA generativa",
];

export let description = "GeniusXP é a plataforma de eventos que utiliza inteligência artificial para otimizar a experiência do participante e gerar insights, antes, durante e depois do evento para a organização.";